"""Added work_company

Revision ID: 08d8e3c87f5f
Revises: 96fddbff6324
Create Date: 2026-01-08 02:36:45.309281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08d8e3c87f5f'
down_revision = '96fddbff6324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_logs')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_company', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('work_company')

    op.create_table('email_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('conversation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('to_email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('body_summary', mysql.TEXT(), nullable=True),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('email_logs_ibfk_1')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('email_logs_ibfk_2')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('email_logs_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
