"""Added buying_role

Revision ID: 2ffdcff9d5a5
Revises: 08d8e3c87f5f
Create Date: 2026-01-08 02:48:01.544709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffdcff9d5a5'
down_revision = '08d8e3c87f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buying_role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('buying_role')

    # ### end Alembic commands ###
