"""Add gender to agent

Revision ID: 3efa3f59629b
Revises: 5ceefc0573e4
Create Date: 2025-12-15 19:14:41.106537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efa3f59629b'
down_revision = '5ceefc0573e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'NEUTRAL', name='agentgender'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
