"""Add google_credentials to User

Revision ID: 5286bd95b4c4
Revises: d0bcae8ef434
Create Date: 2025-12-12 20:46:17.669829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5286bd95b4c4'
down_revision = 'd0bcae8ef434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_credentials', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_credentials')

    # ### end Alembic commands ###
