"""remove_channel_id

Revision ID: 5aec48972901
Revises: 3efa3f59629b
Create Date: 2026-01-03 00:59:25.652911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aec48972901'
down_revision = '3efa3f59629b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointments_ibfk_4'), type_='foreignkey')
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=mysql.ENUM('whatsapp', 'voice', 'sms', 'email', 'webchat', 'admin_chat', 'telegram'),
               type_=sa.String(length=50),
               nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=mysql.ENUM('whatsapp', 'voice', 'sms', 'email', 'webchat', 'admin_chat', 'telegram'),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('whatsapp', 'voice', 'sms', 'email', 'webchat', 'admin_chat', 'telegram'),
               existing_nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('whatsapp', 'voice', 'sms', 'email', 'webchat', 'admin_chat', 'telegram'),
               nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('appointments_ibfk_4'), 'channels', ['channel_id'], ['id'])

    # ### end Alembic commands ###
