"""add provider to agent

Revision ID: 5ceefc0573e4
Revises: 5286bd95b4c4
Create Date: 2025-12-13 16:41:08.484133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ceefc0573e4'
down_revision = '5286bd95b4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephony_provider', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('telephony_provider')

    # ### end Alembic commands ###
