"""Add HubSpot CRM fields to Customer and Conversation

Revision ID: 96fddbff6324
Revises: 5aec48972901
Create Date: 2026-01-04 11:41:02.746162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fddbff6324'
down_revision = '5aec48972901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hubspot_deal_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('funnel_stage', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_hubspot_deal_id'), ['hubspot_deal_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hubspot_contact_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lifecycle_stage', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_hubspot_contact_id'), ['hubspot_contact_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_hubspot_contact_id'))
        batch_op.drop_column('lifecycle_stage')
        batch_op.drop_column('hubspot_contact_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_hubspot_deal_id'))
        batch_op.drop_column('funnel_stage')
        batch_op.drop_column('hubspot_deal_id')

    # ### end Alembic commands ###
