"""Initial migration

Revision ID: d0bcae8ef434
Revises: 
Create Date: 2025-12-12 05:14:55.258984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bcae8ef434'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_gender', sa.Enum('FEMALE', 'MALE', 'NEUTRAL', name='agentgender'), nullable=True),
    sa.Column('personality_prompt', sa.Text(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('voice_provider', sa.String(length=50), nullable=True),
    sa.Column('voice_model', sa.String(length=100), nullable=True),
    sa.Column('api_keys', sa.JSON(), nullable=True),
    sa.Column('pinecone_index', sa.String(length=255), nullable=True),
    sa.Column('pinecone_namespace', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tone', sa.Enum('PROFESSIONAL', 'FRIENDLY', 'FORMAL', 'CASUAL', 'RECEPTIONIST', 'SALES', 'SUPPORT', 'CONCIERGE', name='agenttone'), nullable=True),
    sa.Column('objective', sa.Enum('CUSTOMER_SERVICE', 'SALES', 'SCHEDULING', 'LEAD_QUALIFICATION', 'SUPPORT', 'PAYMENTS', 'INVENTORY', 'GENERAL', name='agentobjective'), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('WHATSAPP', 'VOICE', 'SMS', 'EMAIL', 'WEBCHAT', name='channeltype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DISCONNECTED', 'CONNECTING', 'CONNECTED', 'ERROR', name='channelstatus'), nullable=True),
    sa.Column('status_message', sa.String(length=255), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('qr_expires_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'type', 'phone_number', name='unique_company_channel')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CUSTOMER', 'ADMIN', 'EMPLOYEE', 'INTERNAL', name='conversationtype'), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.Enum('WHATSAPP', 'VOICE', 'SMS', 'EMAIL', 'WEBCHAT', 'ADMIN_CHAT', name='messagechannel'), nullable=False),
    sa.Column('conv_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'TXT', 'CSV', 'XLSX', 'URL', name='documenttype'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pinecone_ids', sa.JSON(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'ERROR', name='documentstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'SALES', 'SUPPORT', 'ADMIN', 'GENERAL', name='employeerole'), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('availability_hours', sa.JSON(), nullable=True),
    sa.Column('can_receive_calls', sa.Boolean(), nullable=True),
    sa.Column('can_receive_messages', sa.Boolean(), nullable=True),
    sa.Column('can_receive_escalations', sa.Boolean(), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'EMPLOYEE', name='userrole'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agent_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('CHANNEL', 'INTEGRATION', 'TONE', 'OBJECTIVE', 'AI_FEATURE', 'TOOL', name='featurecategory'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'name', name='unique_agent_feature')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'VOICE', 'SMS', 'EMAIL', 'WEBCHAT', 'ADMIN_CHAT', name='messagechannel'), nullable=True),
    sa.Column('media_url', sa.String(length=512), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('agent_features')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('employees')
    op.drop_table('documents')
    op.drop_table('conversations')
    op.drop_table('channels')
    op.drop_table('agents')
    op.drop_table('companies')
    # ### end Alembic commands ###
