"""Increase blood_pressure length to 500

Revision ID: 02b395ec372d
Revises: ededbb75407e
Create Date: 2026-03-26 01:29:03.473558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import services.encryption_service

# revision identifiers, used by Alembic.
revision = '02b395ec372d'
down_revision = 'ededbb75407e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_evaluations', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=mysql.VARCHAR(length=50),
               type_=services.encryption_service.EncryptedString(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_evaluations', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=services.encryption_service.EncryptedString(length=500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
