"""add_dlocal_subscription_fields

Revision ID: 122420aaf98a
Revises: 3af26d0119f5
Create Date: 2026-03-21 06:12:01.848527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '122420aaf98a'
down_revision = '3af26d0119f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_courtesy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'plans', ['subscription_plan_id'], ['id'])

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dlocal_plan_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dlocal_plan_token', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('rebill_plan_id'))
        batch_op.create_index(batch_op.f('ix_plans_dlocal_plan_token'), ['dlocal_plan_token'], unique=True)
        batch_op.create_unique_constraint(None, ['dlocal_plan_id'])
        batch_op.drop_column('rebill_plan_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dlocal_subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dlocal_subscription_token', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('rebill_subscription_id'))
        batch_op.create_index(batch_op.f('ix_subscriptions_dlocal_subscription_token'), ['dlocal_subscription_token'], unique=True)
        batch_op.create_unique_constraint(None, ['dlocal_subscription_id'])
        batch_op.drop_column('rebill_subscription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rebill_subscription_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_subscriptions_dlocal_subscription_token'))
        batch_op.create_index(batch_op.f('rebill_subscription_id'), ['rebill_subscription_id'], unique=True)
        batch_op.drop_column('dlocal_subscription_token')
        batch_op.drop_column('dlocal_subscription_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rebill_plan_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_plans_dlocal_plan_token'))
        batch_op.create_index(batch_op.f('rebill_plan_id'), ['rebill_plan_id'], unique=True)
        batch_op.drop_column('dlocal_plan_token')
        batch_op.drop_column('dlocal_plan_id')

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subscription_plan_id')
        batch_op.drop_column('is_courtesy')
        batch_op.drop_column('subscription_active')

    # ### end Alembic commands ###
