"""add_coach_last_research_advice

Revision ID: 42c79b1478de
Revises: eff8548901eb
Create Date: 2026-05-26 13:27:10.354099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c79b1478de'
down_revision = 'eff8548901eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_last_research_advice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('coach_last_research_advice')

    # ### end Alembic commands ###
