"""add diagnostic fields to wellness evaluations

Revision ID: 46cacbb91c50
Revises: 79f4dfe1fc4b
Create Date: 2026-03-24 03:42:57.531842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cacbb91c50'
down_revision = '79f4dfe1fc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_pressure', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pulse', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('energy_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('symptoms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_evaluations', schema=None) as batch_op:
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('observations')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('energy_level')
        batch_op.drop_column('pulse')
        batch_op.drop_column('blood_pressure')

    # ### end Alembic commands ###
