"""add_is_ai_active_to_leads_and_customers

Revision ID: 49b3e7a8053a
Revises: 4564a50c23e2
Create Date: 2026-03-26 05:13:03.076164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b3e7a8053a'
down_revision = '4564a50c23e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('is_ai_active')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_ai_active')

    # ### end Alembic commands ###
