"""Add google_calendar_id to distributors

Revision ID: 78507d528a96
Revises: 122420aaf98a
Create Date: 2026-03-23 23:52:44.550714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78507d528a96'
down_revision = '122420aaf98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_id')

    # ### end Alembic commands ###
