"""add credits_balance

Revision ID: 8271a11a4fd5
Revises: 23babbab9b22
Create Date: 2026-06-10 19:39:45.865153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8271a11a4fd5'
down_revision = '23babbab9b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_balance', sa.Integer(), nullable=True))

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_credit_block', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('credits_granted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paypal_plan_id', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('dlocal_plan_id'))
        batch_op.drop_index(batch_op.f('ix_plans_dlocal_plan_token'))
        batch_op.create_index(batch_op.f('ix_plans_paypal_plan_id'), ['paypal_plan_id'], unique=True)
        batch_op.drop_column('dlocal_plan_token')
        batch_op.drop_column('dlocal_plan_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_subscription_id', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('dlocal_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_dlocal_subscription_token'))
        batch_op.create_index(batch_op.f('ix_subscriptions_paypal_subscription_id'), ['paypal_subscription_id'], unique=True)
        batch_op.drop_column('dlocal_subscription_id')
        batch_op.drop_column('dlocal_subscription_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dlocal_subscription_token', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('dlocal_subscription_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_subscriptions_paypal_subscription_id'))
        batch_op.create_index(batch_op.f('ix_subscriptions_dlocal_subscription_token'), ['dlocal_subscription_token'], unique=True)
        batch_op.create_index(batch_op.f('dlocal_subscription_id'), ['dlocal_subscription_id'], unique=True)
        batch_op.drop_column('paypal_subscription_id')

    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tasks_pending'), ['distributor_id', 'action', 'status'], unique=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dlocal_plan_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('dlocal_plan_token', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_plans_paypal_plan_id'))
        batch_op.create_index(batch_op.f('ix_plans_dlocal_plan_token'), ['dlocal_plan_token'], unique=True)
        batch_op.create_index(batch_op.f('dlocal_plan_id'), ['dlocal_plan_id'], unique=True)
        batch_op.drop_column('paypal_plan_id')
        batch_op.drop_column('credits_granted')
        batch_op.drop_column('is_credit_block')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_leads_phone'), ['phone'], unique=False)

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('credits_balance')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_conv_lookup'), ['distributor_id', 'channel', 'participant_id', 'status'], unique=False)

    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_agent_priority'), ['distributor_id', 'priority'], unique=False)

    # ### end Alembic commands ###
