"""Add bailey_sessions table for WhatsApp integration

Revision ID: ad9235bd9382
Revises: 7f843018eb8d
Create Date: 2026-03-08 17:28:11.488984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9235bd9382'
down_revision = '7f843018eb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bailey_sessions',
    sa.Column('pk_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bailey_sessions')
    # ### end Alembic commands ###
