"""Add whatsapp_connected and whatsapp_phone to distributors

Revision ID: e043b2d2a415
Revises: ad9235bd9382
Create Date: 2026-03-08 19:25:47.444965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e043b2d2a415'
down_revision = 'ad9235bd9382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_connected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_phone')
        batch_op.drop_column('whatsapp_connected')

    # ### end Alembic commands ###
