"""Add searchable hashes to Lead model

Revision ID: ededbb75407e
Revises: 46cacbb91c50
Create Date: 2026-03-26 00:48:56.389126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import services.encryption_service

# revision identifiers, used by Alembic.
revision = 'ededbb75407e'
down_revision = '46cacbb91c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_email_hash'), ['email_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone_hash'), ['phone_hash'], unique=False)

    with op.batch_alter_table('wellness_evaluations', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=mysql.TEXT(),
               type_=services.encryption_service.EncryptedString(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_evaluations', schema=None) as batch_op:
        batch_op.alter_column('blood_pressure',
               existing_type=services.encryption_service.EncryptedString(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_phone_hash'))
        batch_op.drop_index(batch_op.f('ix_leads_email_hash'))
        batch_op.drop_column('phone_hash')
        batch_op.drop_column('email_hash')

    # ### end Alembic commands ###
