"""add_coach_columns

Revision ID: eff8548901eb
Revises: 5ac2ce61557c
Create Date: 2026-05-26 12:46:02.666754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff8548901eb'
down_revision = '5ac2ce61557c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_mode_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('coach_music_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coach_level_progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coach_daily_tasks_status', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('coach_daily_tasks_status')
        batch_op.drop_column('coach_level_progress')
        batch_op.drop_column('coach_music_preference')
        batch_op.drop_column('coach_mode_enabled')

    # ### end Alembic commands ###
