"""Add searchable hashes to Customer model

Revision ID: fe2419b54fd6
Revises: 02b395ec372d
Create Date: 2026-03-26 02:09:52.899115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2419b54fd6'
down_revision = '02b395ec372d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_email_hash'), ['email_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone_hash'), ['phone_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone_hash'))
        batch_op.drop_index(batch_op.f('ix_customers_email_hash'))
        batch_op.drop_column('phone_hash')
        batch_op.drop_column('email_hash')

    # ### end Alembic commands ###
